[package]
name = "ymlfxr"
version = "0.3.2"
authors = ["Brett Smith <bc.smith@sas.com>"]
edition = "2018"
description = "rust cli for formatting yaml v1.2 that passes yamllint with default settings"
homepage = "https://github.com/xbcsmith/ymlfxr"
license = "Apache-2.0"
keywords = ["yaml", "yamllint"]
categories = ["command-line-utilities"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1"
yaml-rust2 = "0.10"
ulid = "1.0"
bytebuffer = "2.1"
